FROM python:3.11

COPY requirements_email.txt ./requirements.txt

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ./email/app /app
COPY ./resources /app/resources
COPY passwords.json /app/passwords.json

WORKDIR /app

CMD ["python", "email_main.py"]