FROM python:3.11

WORKDIR /app

COPY requirements.txt .

RUN pip install -U pip && pip install -r requirements.txt

COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

COPY api/ ./api
COPY passwords.json /app/passwords.json

EXPOSE 8000

# Command to start the API, including waiting for the database
CMD ["./wait-for-it.sh", "database:3306", "--", "gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "api.main:app"]