# Dockerfile
FROM ollama/ollama:0.3.14

# Copiar el script de inicio en el contenedor
COPY startup.sh /root/startup.sh

# Dar permisos de ejecución al script
RUN chmod +x /root/startup.sh

# Definir el script de inicio como entrypoint
ENTRYPOINT ["/bin/sh", "-c", "/root/startup.sh"]
